import { Outfit, Lora } from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const lora = Lora({
  weights: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio - Harris",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${outfit.variable} ${lora.variable} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
  );
}
